listen=YES
listen_ipv6=NO

anonymous_enable=YES
local_enable=YES
write_enable=YES
chroot_local_user=YES

allow_writeable_chroot=YES

no_anon_password=YES
anon_root=/srv/ftp
anon_upload_enable=NO
anon_mkdir_write_enable=NO

xferlog_enable=YES
log_ftp_protocol=YES
