#!/bin/bash

# Most of the following codes are generated by AI, i had trouble figuring out the answers.

REPORT="security_report.txt"
TEMP_CONN="conn_counts.txt"
TEMP_FAILS="ssh_failed.txt"
TEMP_PORTS="unusual_ports.txt"

echo -e "Security Report - $(date)\n" > "$REPORT"

# IPs with more than 100 connections

echo "----- IPs with more than 100 connections -----" >> "$REPORT"

netstat -ntu 2>/dev/null | awk 'NR>2 {print $5}' | \
cut -d: -f1 | \
grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | \
sort | uniq -c | sort -nr | awk '$1 > 100 {print $2, $1}' > "$TEMP_CONN"

if [ -s "$TEMP_CONN" ]; then
    cat "$TEMP_CONN" >> "$REPORT"
else
    echo "No suspicious IPs found." >> "$REPORT"
fi

echo "" >> "$REPORT"

# Failed SSH login attempts from logs

echo "----- Failed SSH login attempts (Failed password) -----" >> "$REPORT"

if [ -f /var/log/auth.log ]; then
    sudo grep "Failed password" /var/log/auth.log > "$TEMP_FAILS" 2>/dev/null
elif [ -f /var/log/secure ]; then
    sudo grep "Failed password" /var/log/secure > "$TEMP_FAILS" 2>/dev/null
else
    echo "No auth log file found." >> "$REPORT"
    > "$TEMP_FAILS"
fi

FAILED_COUNT=$(wc -l < "$TEMP_FAILS")
echo "Total failed SSH login attempts: $FAILED_COUNT" >> "$REPORT"

if [ "$FAILED_COUNT" -gt 0 ]; then
    echo "Sample failed login entries:" >> "$REPORT"
    head -n 10 "$TEMP_FAILS" >> "$REPORT"
fi

echo "" >> "$REPORT"

# IPs connected to unusual ports with >10000 connections

echo "----- IPs connected to unusual ports (ports >10000 connections) -----" >> "$REPORT"

netstat -ntu 2>/dev/null | awk 'NR>2 {print $4, $5}' | \
awk -F'[: ]+' '
{
    ip=$6
    port=$4
    if (ip ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && port !~ /^(22|80|443|53|25|110|143|3306|5432)$/) {
        print ip ":" port
    }
}' | sort | uniq -c | sort -nr | awk '$1 > 10000 {print $2, $1}' > "$TEMP_PORTS"

if [ -s "$TEMP_PORTS" ]; then
    cat "$TEMP_PORTS" >> "$REPORT"
else
    echo "No suspicious high-volume unusual-port connections found." >> "$REPORT"
fi

echo "" >> "$REPORT"
echo "Report saved to $REPORT"

# Cleanup temp files
rm -f "$TEMP_CONN" "$TEMP_FAILS" "$TEMP_PORTS"
