#!/usr/bin/env bash

# top 5 ips section is generated by AI
# put your interface in IFACE variable!

IFACE="wlp2s0"
INTERVAL=5
LOGFILE="monitoring_log.txt"

while true; do
  ts=$(date "+%Y-%m-%d %H:%M:%S")
# --- Bandwidth: ifstat (Hint 1) ---
  bw_line=$(ifstat -i "$IFACE" 1 5 2>/dev/null)
# --- Interface statistics: /proc/net/dev (Hint 2) ---
  iface_line=$(grep -w "$IFACE" /proc/net/dev 2>/dev/null)
# --- Active connections: ss -ntu | wc -l (Hint 3) ---
  active=$(ss -ntu 2>/dev/null | wc -l)
# --- Top 5 IP addresses: using netstat (Hint 4) ---
top5=$(
    netstat -ntu 2>/dev/null |
      awk '
        {
          for (i=1; i<=NF; i++) {
            if ($i ~ /([0-9]{1,3}\.){3}[0-91,3}:[0-9]+$/) {
              ip=$i
              sub(/:[0-9]+$/, "", ip)
              cnt[ip]++
            }
          }
        }
        END {
          for (ip in cnt) print cnt[ip], ip
        }' |
      sort -nr |
      head -n 5 |
      awk '{printf "%s=%s ", $2, $1}'
  )
  {
    echo "---------------------------------------------------"
    echo -e "[$ts] Interface=$IFACE\n"
    echo -e "----- Bandwidth -----\n $bw_line\n"
    echo -e "----- /proc/net/dev -----\n $iface_line\n"
    echo -e "----- ActiveConnections -----\n $active\n"
    echo -e "----- Top 5 IPs -----\n ${top5:-N/A}\n"
  } >> "$LOGFILE"
done
